from tests.newmath import example,test_factor

example.test_deberia_saludar_a_mundo()
example.test_deberia_saludar_a_una_persona()
test_factor.test_deberia_validar_un_numero_negativo()
test_factor.test_deberia_validar_si_el_numero_negativo_cambia_resultado()
test_factor.test_deberia_validar_si_el_numero_aplica_al_rango_3()
test_factor.test_deberia_validar_la_posicion_4_de_fibonacci_iniciando_desde_0()
test_factor.test_deberia_validar_la_posicion_3_de_fibonacci_iniciando_desde_3_y_5()